print("Hello world!")
print("Hello Again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not.' ")
print('I"said" do not touch this.')
print("repeat this once more time.")
print('check "double quotes  "in single quotes')
